# Generated by Django 4.1.1 on 2023-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_blogs_alter_contact_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("img", models.ImageField(blank="True", null="True", upload_to="pics")),
            ],
        ),
    ]
