# Generated by Django 4.1.1 on 2023-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="img",
            field=models.ImageField(blank="True", null="True", upload_to="images"),
        ),
    ]
