# Generated by Django 4.1.1 on 2023-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_blogs_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank="True",
                        null="True",
                        upload_to="static/assets/images/Gallery",
                    ),
                ),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
