# Generated by Django 4.1.1 on 2023-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(blank="True", null="True", upload_to="Gallery"),
        ),
    ]
