# Generated by Django 4.1.1 on 2023-02-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_registration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="person_select",
            new_name="select_course",
        ),
    ]
