# Generated by Django 4.1.1 on 2023-02-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_placements"),
    ]

    operations = [
        migrations.DeleteModel(name="Placements",),
    ]
